---
title: 'Session 4: challenge creating publish graphics demo'
author: "Christopher"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("D:/OneDrive - KMITL/Documents/GitHub-repo/training-data-viz/04_challenge_plot/")

```


```{r}
library(tidyverse)
library(janitor)
library(ggthemes)
library(ggrepel)
library(viridis)
library(readxl)
```


## Corruption and developemnt: Corrosive corruption

A correlation between corruption and development

https://www.economist.com/blogs/dailychart/2011/12/corruption-and-development&lt;/a&gt;&lt;a

```{r}
region <- c("East EU Cemt Asia", "Americas", "Asia Pacific",
            "EU W. Europe", "MENA", "SSA")

region_name<- c("OECD", "Americas", "Asia & Oceania",
                "Central & Eastern Europe",
                "Middle East & north Africa", 
                "Sub-Saharan Africa")

data_label <- tibble(region, region_name)


pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                   "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                   "India", "Italy", "China", "South Africa", "Spane",
                   "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                   "United States", "Germany", "Britain", "Barbados", "Norway", 
                   "Japan", "New Zealand", "Singapore", "Philippines")

clr <- c("#006D6F", "steelblue2", "lightskyblue1" , "seagreen",
         "indianred1", "brown", "tomato")

names(clr) <- c(as.character(data_label$region_name))


economist_data <- read_csv("data/Economist_Assignment_Data.csv", "Rsq=52%") %>% 
  clean_names() %>%
  select(-x1) %>% 
  left_join(data_label, by = "region")


```

```{r}
economist_data %>% 
ggplot(mapping = aes(x = cpi, y = hdi)) +
  stat_smooth(aes(fill = "Rsq=52%"),
              method = "lm",
              se = FALSE,
              formula = y ~ log(x),
              color = "tomato"
              ) +
    geom_point(size = 3, 
             fill = "white", 
             shape = 21, 
             stroke = 1.3,
             aes(color = region_name)) +
  geom_text_repel(aes(label = ifelse(country %in% pointsToLabel, country, NA)),
                  color = "gray20",
                  point.padding = unit(0.025, "npc"),
                  force = 1,
                  nudge_x = -0.015,
                  nudge_y = 0.03
                  ) + 
  scale_color_manual(values = clr,
                     breaks = c("OECD", "Americas", "Asia & Oceania",
                                "Central & Eastern Europe",
                                "Middle East & north Africa", 
                                 "Sub-Saharan Africa","Rsq=52%"),
                     labels = c("OECD", "Americas", "Asia &\n Oceania",
                                "Central &\n Eastern Europe",
                                "Middle East &\n north Africa", 
                                 "Sub-Saharan Africa","Rsq=52%")) +
  scale_x_continuous(breaks = seq(1, 10, 1),
                     limits = c(1, 10)) +
  scale_y_continuous(breaks = seq(0.2, 1.0, 0.1),
                     limits = c(0.2, 1.0)) +
  theme_minimal() +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
        plot.title = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(size = 1),
        legend.position = "top",
        plot.caption = element_text(hjust = 0),
        axis.ticks.x = element_line(),
        axis.line.x = element_line(color = "gray", lineend = "round")) +
  guides(color = guide_legend(nrow = 1, title = ""),
         fill = guide_legend(title = "")) +
  labs(title = "Corruption and human development",
       caption = "Sources: Transparancy International; UN Development Report",
       x = expression(italic("Corruption Perception Index, 2011 (10 = least corrup)")),
       y = expression(italic("Human Development Index, 2011 (1 = best)"))
  )

ggsave("image/economist_graphics.jpeg", height = 6, width = 10, units = "in" )

```



## Philippine Statistic Authority (PSA)

https://psa.gov.ph/foreign-investments/technical-notes

```{r}
psa_data <- read_excel("data/psa_gdp_rate.xlsx") %>% 
  mutate(quarter_year = paste(quarter, year)) %>% 
  select(quarter_year, gdp_rate) %>% 
  mutate(row = row_number())

```


```{r}
psa_data %>% 
  ggplot(aes(x = reorder(quarter_year, row), 
             y  = gdp_rate, group = 1)) +
  geom_hline(yintercept = 0, 
             color = "deepskyblue", 
             size = 0.7) +
  geom_point(size = 4, color = "dodgerblue3") +
  geom_segment(aes(y = 0, yend = gdp_rate, xend = quarter_year),
               # data = subset(psa_data, gdp_rate < 0),
               color = "dodgerblue3",
               linetype = "dashed") +
  geom_line(size = 0.7, color = "dodgerblue3") +
  geom_text(aes(label = gdp_rate),
                  data = subset(psa_data, gdp_rate > 0),
                  nudge_y = 1.4) +
  geom_text(aes(label = gdp_rate),
            data = subset(psa_data, gdp_rate < 0),
            nudge_y = -1.7,
            nudge_x = -0.1) +
  theme_void() +
  theme(plot.margin = margin(0.5, 1, 1, 1, "cm"),
        plot.title = element_text(hjust = 0.5, 
                                  size = 12, 
                                  face = "bold"),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x  = element_text(vjust = 175, 
                                    size = 7,
                                    face = "bold"),
        axis.text.y = element_blank(),
        plot.caption = element_text(hjust = 0,
                                    size = 12,
                                    color = "grey40")) +
  labs(title = "Figure 1. Gross Domestic Product (At Constant 2018 Price)",
       subtitle = "Year-on-Year Growth Rates (in percent)\n Q1 2018-2019 to Q3 2020-2021",
       caption = "Source: Philippine Statistics Authority")


ggsave("image/psa_gdp.jpeg", height = 7.3, width = 10, units = "in")


```

